name: API Test CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ApiTestsJestSupertest
        run: npm install

      - name: Set up environment variables
        working-directory: ApiTestsJestSupertest
        run: |
          echo "GOREST_API_TOKEN=${{ secrets.GOREST_API_TOKEN }}" >> .env
          echo "GOREST_BASE_URL=${{ secrets.GOREST_BASE_URL }}" >> .env

      - name: Run tests
        working-directory: ApiTestsJestSupertest
        run: npm test
