name: API Test CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List repository contents
        run: ls -la

      - name: Navigate to project directory
        run: |
          cd ApiTestsJestSupertest
          ls -la

      - name: Install dependencies
        run: npm install
        working-directory: ApiTestsJestSupertest

      - name: Set up environment variables
        run: |
          echo "GOREST_API_TOKEN=${{ secrets.GOREST_API_TOKEN }}" >> .env
          echo "GOREST_BASE_URL=${{ secrets.GOREST_BASE_URL }}" >> .env
        working-directory: ApiTestsJestSupertest

      - name: Run tests
        run: npm test
        working-directory: ApiTestsJestSupertest
